"""WeasyPrint-based PDF generation.

Renders a board-ready PDF from markdown. Output is attached to the agent
state's `artifacts` list so the channel adapter can upload it.
"""

from __future__ import annotations

import asyncio
import base64
import re

from pydantic import BaseModel, Field

from ..base import Tool, ToolContext, ToolError
from ..registry import default_registry

_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{title}</title>
<style>
  @page {{ size: A4; margin: 24mm 18mm; }}
  body {{ font-family: 'Liberation Sans', Helvetica, Arial, sans-serif; color: #0f172a;
          font-size: 11pt; line-height: 1.5; }}
  h1 {{ color: #0f172a; font-size: 22pt; margin: 0 0 4mm; border-bottom: 2px solid #0f172a;
        padding-bottom: 2mm; }}
  h2 {{ color: #1e3a8a; font-size: 14pt; margin: 8mm 0 3mm; }}
  h3 {{ color: #1e3a8a; font-size: 12pt; margin: 6mm 0 2mm; }}
  table {{ border-collapse: collapse; width: 100%; margin: 4mm 0; font-size: 10pt; }}
  th, td {{ border: 1px solid #cbd5e1; padding: 2mm 3mm; text-align: left; }}
  th {{ background: #e2e8f0; }}
  code {{ background: #f1f5f9; padding: 1px 4px; border-radius: 3px; font-size: 10pt; }}
  pre {{ background: #f1f5f9; padding: 3mm; border-radius: 4px; overflow-x: auto; }}
  blockquote {{ margin: 4mm 0; padding-left: 4mm; border-left: 3px solid #94a3b8; color: #475569; }}
  .footer {{ position: fixed; bottom: 8mm; left: 18mm; right: 18mm;
             font-size: 9pt; color: #64748b; text-align: center; }}
</style>
</head>
<body>
{body_html}
<div class="footer">{footer}</div>
</body>
</html>"""


def _markdown_to_html(md: str) -> str:
    """Tiny markdown-ish to HTML converter (avoids adding markdown dep).

    Supports h1-h3, bullet lists, code fences, bold/italic, paragraphs,
    and pipe tables. Sufficient for AI-generated reports.
    """
    lines = md.splitlines()
    out: list[str] = []
    in_list = False
    in_code = False
    code_buf: list[str] = []
    table_buf: list[str] = []

    def flush_list() -> None:
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    def flush_table() -> None:
        nonlocal table_buf
        if not table_buf:
            return
        rows = [
            [c.strip() for c in r.strip().strip("|").split("|")]
            for r in table_buf
            if r.strip().startswith("|")
        ]
        if len(rows) < 2:
            table_buf = []
            return
        header, _sep, *body_rows = rows
        out.append("<table><thead><tr>")
        out.extend(f"<th>{c}</th>" for c in header)
        out.append("</tr></thead><tbody>")
        for r in body_rows:
            out.append("<tr>")
            out.extend(f"<td>{c}</td>" for c in r)
            out.append("</tr>")
        out.append("</tbody></table>")
        table_buf = []

    for raw in lines:
        line = raw.rstrip()

        if line.startswith("```"):
            if in_code:
                out.append("<pre><code>" + "\n".join(code_buf) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                flush_list()
                flush_table()
                in_code = True
            continue
        if in_code:
            code_buf.append(line)
            continue

        if "|" in line and line.strip().startswith("|"):
            flush_list()
            table_buf.append(line)
            continue
        else:
            flush_table()

        if not line.strip():
            flush_list()
            out.append("")
            continue
        if line.startswith("### "):
            flush_list()
            out.append(f"<h3>{line[4:]}</h3>")
            continue
        if line.startswith("## "):
            flush_list()
            out.append(f"<h2>{line[3:]}</h2>")
            continue
        if line.startswith("# "):
            flush_list()
            out.append(f"<h1>{line[2:]}</h1>")
            continue
        if line.startswith(("- ", "* ")):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{line[2:]}</li>")
            continue

        flush_list()
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
        text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
        text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
        out.append(f"<p>{text}</p>")

    flush_list()
    flush_table()
    return "\n".join(out)


class PdfFromMarkdownInput(BaseModel):
    title: str
    markdown: str = Field(description="Body markdown. Headings, lists, tables supported.")
    filename: str = Field(default="report.pdf")
    footer: str = Field(default="Generated by Coworker AI")


class PdfFromMarkdownOutput(BaseModel):
    filename: str
    size_bytes: int
    content_b64: str = Field(description="Base64-encoded PDF bytes for transport.")


class PdfFromMarkdown(Tool[PdfFromMarkdownInput, PdfFromMarkdownOutput]):
    name = "artifact.pdf.from_markdown"
    description = (
        "Render a board-ready PDF from a markdown body. Output bytes are uploaded "
        "to Slack as a file attachment in the same thread."
    )
    provider = ""
    Input = PdfFromMarkdownInput
    Output = PdfFromMarkdownOutput

    async def run(self, ctx: ToolContext, args: PdfFromMarkdownInput) -> PdfFromMarkdownOutput:
        from weasyprint import HTML

        html_body = _markdown_to_html(args.markdown)
        html = _HTML_TEMPLATE.format(title=args.title, body_html=html_body, footer=args.footer)

        def _render() -> bytes:
            return HTML(string=html).write_pdf()

        try:
            pdf = await asyncio.to_thread(_render)
        except Exception as exc:
            raise ToolError(f"PDF render failed: {exc}") from exc

        # Side-effect: append to ctx.extra so the executor can lift it onto state.artifacts
        ctx.extra.setdefault("artifacts", []).append(
            {
                "kind": "pdf",
                "filename": args.filename,
                "content_b64": base64.b64encode(pdf).decode("ascii"),
                "description": args.title,
            }
        )

        return PdfFromMarkdownOutput(
            filename=args.filename,
            size_bytes=len(pdf),
            content_b64=base64.b64encode(pdf).decode("ascii"),
        )


default_registry.register(PdfFromMarkdown())
